### PR TITLE
Added an option to reuse the last fighter.

### PR DESCRIPTION
**Pull request by RychuP**
Just a small change to your code. I found entering a name for a new player after each game a bit annoying. Choosing "Y" or just pressing enter reuses the previously created fighter.

This is more of an exercise in opening pull requests rather than a meaningful contribution.

### CODE REVIEW

**Comment by RychuP** [comment]
Lol. I can already see that the savedPlayer variable is completely unnecessary. Oh, never mind.

**Comment by MrFusion3000** [comment]
Hi,
Nice that you found my little space. And thanks for your feedback.
Yes, there are a lot of things that needs changing or implemented. Arena Fighter was an assignment in a course I took, there was no need to save the player. Now I'm building on it further as a reminder of basics and to take it further, so I'm implementing a highscore list saved to a text file and I might do the same with the player stats. :)


/Nicolas

7 september 2021, 03:48 centraleuropeisk sommartid, skrev Ryszard ***@***.***>:

**Comment by RychuP** [comment]
Yes, I noticed your code was an exercise. This is why I wrote this small modification to try the pull requests on git hub and make it an exercise for myself too. Have you review my changes?

**Comment by MrFusion3000** [comment]
Yes, looks good. Maybe I'll use it.

7 september 2021 10:55:01 +02:00, skrev Ryszard Pyka ***@***.***>:

**Pull request closed without merging**
